'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Map as MapIcon,Shield,Crosshair,Maximize,Minimize,Plus,Minus,RotateCcw,X,Menu,Move,ChevronDown,Info,Handshake,Check,Compass} from 'lucide-react';
const places=[{name:'Woodbury',grid:'A3',x:190,y:470,type:'safe',note:'Safe zone somente dentro da comunidade.'},{name:'Hilltop',grid:'G4',x:978,y:608,type:'safe',note:'Safe zone somente dentro da comunidade.'},{name:'Alexandria',grid:'D6 / E6',x:622,y:937,type:'safe',note:'Safe zone somente dentro da comunidade.'},{name:'Sanctuary',grid:'G6',x:1011,y:890,type:'safe',note:'Safe zone somente dentro da comunidade.'},{name:'Terminus',grid:'D4',x:586,y:592,type:'trade',note:'Safe zone para trocas somente dentro de D4.'}];
function Discord(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M19.7 5.1A18 18 0 0 0 15.3 3.7l-.6 1.2a16 16 0 0 0-5.4 0l-.6-1.2a18 18 0 0 0-4.4 1.4C1.5 9.3.8 13.4 1.2 17.5a18 18 0 0 0 5.5 2.8l1.1-1.8-1.7-.8.4-.3c3.5 1.6 7.5 1.6 11 0l.4.3-1.7.8 1.1 1.8a18 18 0 0 0 5.5-2.8c.5-4.8-.8-8.9-3.1-12.4ZM8.5 14.9c-1.1 0-1.9-1-1.9-2.1s.8-2.1 1.9-2.1 1.9 1 1.9 2.1-.8 2.1-1.9 2.1Zm7 0c-1.1 0-1.9-1-1.9-2.1s.8-2.1 1.9-2.1 1.9 1 1.9 2.1-.8 2.1-1.9 2.1Z"/></svg>}
function WorldMap(){
 const el=useRef<HTMLDivElement>(null),pointers=useRef(new Map<number,{x:number,y:number}>()),pendingFocus=useRef<number|null>(null);const [mode,setMode]=useState('territory'),[selected,setSelected]=useState<number|null>(null),[full,setFull]=useState(false),[error,setError]=useState('');const [size,setSize]=useState({w:900,h:580}),[view,setView]=useState({x:0,y:0,s:.5});const current=useRef(view);current.current=view;const world=mode==='territory'?{w:1283,h:1226}:{w:1226,h:1283};
 const fit=useCallback(()=>{if(!el.current)return;const w=el.current.clientWidth,h=el.current.clientHeight,s=Math.min(w/world.w,h/world.h)*.94;setSize({w,h});if(pendingFocus.current!==null){const p=places[pendingFocus.current],z=Math.max(.9,s);setView({x:w/2-p.x*z,y:h/2-p.y*z,s:z});pendingFocus.current=null}else setView({x:(w-world.w*s)/2,y:(h-world.h*s)/2,s});},[world.w,world.h]);
 useEffect(()=>{fit();const observer=new ResizeObserver(fit);if(el.current)observer.observe(el.current);return()=>observer.disconnect()},[fit]);
 const zoom=useCallback((factor:number,cx?:number,cy?:number)=>setView(v=>{const s=Math.max(Math.min(size.w/world.w,size.h/world.h)*.8,Math.min(3.5,v.s*factor)),x=cx??size.w/2,y=cy??size.h/2;return{x:x-(x-v.x)*s/v.s,y:y-(y-v.y)*s/v.s,s}}),[size,world.w,world.h]);
 useEffect(()=>{const target=el.current;if(!target)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=target.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)};target.addEventListener('wheel',wheel,{passive:false});return()=>target.removeEventListener('wheel',wheel)},[zoom]);
 useEffect(()=>{const change=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change)},[]);
 const focus=(i:number)=>{if(mode!=='territory')pendingFocus.current=i;setMode('territory');setSelected(i);const p=places[i],s=Math.max(.9,current.current.s);setView({s,x:size.w/2-p.x*s,y:size.h/2-p.y*s})};
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.getElementById('map-shell')?.requestFullscreen()}catch{setError('Tela cheia indisponível neste navegador.')}};
 return <div id="map-shell" className="map-shell"><div className="map-toolbar"><div className="map-tabs" role="tablist" aria-label="Versão do mapa">{[['territory','Território'],['rules','Zonas & PvP']].map(([value,label])=><button key={value} role="tab" aria-selected={mode===value} className={mode===value?'active':''} onClick={()=>{setMode(value);setSelected(null)}}>{label}</button>)}</div><span className="map-tool-label"><Compass size={16}/> MAPA DO SERVIDOR</span><button className="icon-btn" aria-label={full?'Sair da tela cheia':'Tela cheia'} title="Tela cheia" onClick={fullscreen}>{full?<Minimize size={19}/>:<Maximize size={19}/>}</button></div>
 <div className="map-body"><aside className="map-sidebar"><div className="side-label">PONTOS DE REFERÊNCIA <span>05</span></div><p className="sidebar-hint">Escolha um local para encontrar no mapa.</p><div className="location-list">{places.map((p,i)=><button key={p.name} className={'location '+(selected===i?'selected':'')} onClick={()=>focus(i)}><span className={'location-symbol '+p.type}>{p.type==='safe'?<Shield size={18}/>:<Handshake size={18}/>}</span><span><strong>{p.name}</strong><small>{p.type==='safe'?'Safe zone':'Zona de trocas'}</small></span><span className="grid-tag">{p.grid}</span></button>)}</div><div className="side-warning"><Crosshair size={20}/><strong>FORA DAS ZONAS,<br/>O PvP ESTÁ LIBERADO.</strong><p>Sem exceção. Planeje sua rota antes de sair.</p></div></aside>
 <div ref={el} className="map-viewport" tabIndex={0} role="region" aria-label="Mapa interativo. Use mais e menos para zoom, setas para mover e Home para centralizar."
 onKeyDown={e=>{if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoom(1.25);if(e.key==='-')zoom(.8);if(e.key==='Home')fit();if(e.key.startsWith('Arrow'))setView(v=>({...v,x:v.x+(e.key==='ArrowLeft'?60:e.key==='ArrowRight'?-60:0),y:v.y+(e.key==='ArrowUp'?60:e.key==='ArrowDown'?-60:0)}))}}
 onPointerDown={e=>{if((e.target as HTMLElement).closest('button'))return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}}
 onPointerMove={e=>{const prev=pointers.current.get(e.pointerId);if(!prev)return;const other=[...pointers.current.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){const old=Math.hypot(prev.x-other.x,prev.y-other.y),next=Math.hypot(e.clientX-other.x,e.clientY-other.y),r=e.currentTarget.getBoundingClientRect();if(old>0)zoom(next/old,(e.clientX+other.x)/2-r.left,(e.clientY+other.y)/2-r.top)}else setView(v=>({...v,x:v.x+e.clientX-prev.x,y:v.y+e.clientY-prev.y}));pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}}
 onPointerUp={e=>pointers.current.delete(e.pointerId)} onPointerCancel={e=>pointers.current.delete(e.pointerId)} onLostPointerCapture={e=>pointers.current.delete(e.pointerId)}>
 <div className="map-world" style={{width:world.w,height:world.h,transform:`translate(${view.x}px,${view.y}px) scale(${view.s})`}}><img src={mode==='territory'?'/assets/mapa-territorial.jpg':'/assets/mapa-regras.jpg'} alt={mode==='territory'?'Mapa territorial de TWD Brasil com grade A–H e 1–8.':'Mapa com safe zones em verde, zona de trocas em amarelo e regra de PvP.'} draggable={false}/>{mode==='territory'&&places.map((p,i)=><button key={p.name} aria-label={'Ver '+p.name} className={'map-pin '+p.type+(selected===i?' chosen':'')} style={{left:p.x,top:p.y,transform:`translate(-50%,-50%) scale(${1/view.s})`}} onClick={()=>setSelected(i)}><span>{p.type==='safe'?<Shield size={14}/>:<Handshake size={14}/>}</span></button>)}</div>
 <div className="map-controls"><button className="icon-btn" aria-label="Ampliar mapa" onClick={()=>zoom(1.3)}><Plus size={21}/></button><button className="icon-btn" aria-label="Diminuir mapa" onClick={()=>zoom(1/1.3)}><Minus size={21}/></button><span/><button className="icon-btn" aria-label="Centralizar mapa" onClick={()=>{fit();setSelected(null)}}><RotateCcw size={18}/></button></div><div className="map-compass">N<Compass size={27}/></div>
 {selected!==null&&mode==='territory'&&<div className="map-detail" role="status"><span className={'detail-badge '+places[selected].type}>{places[selected].type==='safe'?<Shield size={16}/>:<Handshake size={16}/>} {places[selected].type==='safe'?'SAFE ZONE':'TROCAS'}</span><button className="close-detail" aria-label="Fechar detalhes" onClick={()=>setSelected(null)}><X size={18}/></button><h3>{places[selected].name}</h3><p>{places[selected].note}</p><small>REFERÊNCIA NA GRADE · {places[selected].grid}</small></div>}{error&&<span className="map-error" role="status">{error}</span>}</div></div>
 <div className="map-bottom"><span><Move size={15}/> Arraste para explorar <span className="desktop-only">· Role para ampliar</span></span><span><i className="legend-dot safe"/> Safe zone <i className="legend-dot trade"/> Trocas</span></div></div>
}
export default function Home(){const [login,setLogin]=useState(false),[menu,setMenu]=useState(false);const modal=useRef<HTMLDivElement>(null),lastFocus=useRef<HTMLElement|null>(null);useEffect(()=>{if(!login)return;lastFocus.current=document.activeElement as HTMLElement;modal.current?.querySelector<HTMLButtonElement>('button')?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setLogin(false);if(e.key==='Tab'){const buttons=modal.current?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);lastFocus.current?.focus()}},[login]);
return <><a className="skip-link" href="#mapa">Ir para o mapa</a><header className="header"><a className="wordmark" href="#inicio" aria-label="TWD Brasil Online, início"><span className="logo-mark">TWD<span className="red-mark"/></span><span className="logo-name">BRASIL<span>ONLINE</span></span></a><nav className={menu?'nav open':'nav'} aria-label="Navegação principal">{[['inicio','Início'],['mapa','Mapa do mundo'],['regras','Zonas & regras']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><button className="discord-btn" onClick={()=>setLogin(true)}><Discord/><span>Entrar com Discord</span></button><button className="mobile-menu icon-btn" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section id="inicio" className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="hero-grain"/><div className="hero-content"><div className="eyebrow"><span/> SERVIDOR BRASILEIRO <b>/</b> ROBLOX</div><p className="hero-overline">THE</p><h1>WALKING<br/>DEAD<span>BRASIL ONLINE</span></h1><p className="hero-description">O mundo que você conhece já não existe.<br/>Encontre seu grupo. Escolha seu caminho. Sobreviva.</p><div className="hero-actions"><a className="primary-btn" href="#mapa"><MapIcon size={20}/> EXPLORAR O MAPA</a><button className="secondary-btn" onClick={()=>setLogin(true)}><Discord/> ENTRAR COM DISCORD</button></div><div className="hero-footnote"><span className="tiny-line"/>THE WALKING DEAD ONLINE · COMUNIDADE BRASILEIRA</div></div><div className="hero-number" aria-hidden="true">BR<span>01 / SOBREVIVÊNCIA</span></div><a className="scroll-cue" href="#mapa"><span>CONHEÇA O TERRITÓRIO</span><ChevronDown size={20}/></a><div className="hero-bottom"><span>UM NOVO MUNDO. AS SUAS DECISÕES.</span><span>TWD / BRASIL</span></div></section>
<section id="mapa" className="map-section"><div className="section-top"><div><div className="eyebrow"><span/> RECONHECIMENTO DE TERRITÓRIO</div><h2>CONHEÇA O <em>MAPA.</em></h2></div><p>Localize sua comunidade e conheça as zonas<br className="desktop-only"/> antes de colocar os pés na estrada.</p></div><WorldMap/></section>
<section id="regras" className="rules-section"><div className="section-top"><div><div className="eyebrow"><span/> ANTES DE SAIR DO ABRIGO</div><h2>AS REGRAS DO <em>MUNDO.</em></h2></div><p>As marcações não protegem toda a região.<br className="desktop-only"/> Respeite os limites de cada zona.</p></div><div className="rules-grid"><article className="rule-card safe-card"><div className="rule-heading"><Shield size={26}/><span>01 / PROTEÇÃO</span></div><h3>SAFE ZONES</h3><p>Woodbury, Hilltop, Alexandria e Sanctuary.</p><div className="rule-scope"><Check size={17}/><strong>Somente dentro da comunidade.</strong></div><p className="rule-note">A proteção não se estende a toda a quadrícula ou às estradas próximas.</p></article><article className="rule-card trade-card"><div className="rule-heading"><Handshake size={26}/><span>02 / NEGOCIAÇÃO</span></div><h3>ZONA DE TROCAS</h3><p>Terminus · referência D4.</p><div className="rule-scope"><Check size={17}/><strong>Somente dentro de D4.</strong></div><p className="rule-note">A área marcada em amarelo no mapa é a safe zone para trocas.</p></article><article className="rule-card pvp-card"><div className="rule-heading"><Crosshair size={26}/><span>03 / COMBATE</span></div><h3>PvP LIBERADO</h3><p>Todo o restante do mapa.</p><div className="rule-scope"><Info size={17}/><strong>Sem exceção.</strong></div><p className="rule-note">Ao sair das zonas protegidas, você entra em território de PvP.</p></article></div><div className="rules-reference"><MapIcon size={17}/><span>Confira os limites na versão <strong>“Zonas & PvP”</strong> do mapa.</span><a href="#mapa">CONSULTAR MAPA</a></div></section></main>
<footer><a className="footer-brand" href="#inicio">TWD <span>BRASIL ONLINE</span></a><p>Comunidade brasileira de The Walking Dead Online no Roblox.<br/>Projeto independente de fãs.</p><span className="footer-version">PRIMEIRA VERSÃO / 2026</span></footer>
{login&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setLogin(false)}}><div ref={modal} className="login-modal" role="dialog" aria-modal="true" aria-labelledby="login-title" aria-describedby="login-description"><button className="modal-close icon-btn" aria-label="Fechar" onClick={()=>setLogin(false)}><X size={22}/></button><div className="discord-orb"><Discord/></div><div className="eyebrow">IDENTIDADE DO SOBREVIVENTE</div><h2 id="login-title">ENTRAR COM DISCORD</h2><p id="login-description">O acesso pelo Discord ainda não está ativo. Enquanto isso, o mapa e as regras já estão disponíveis para explorar.</p><div className="login-state"><Info size={18}/><span>Vinculação com Discord em preparação.</span></div><button className="primary-btn" onClick={()=>{setLogin(false);document.getElementById('mapa')?.scrollIntoView({behavior:'smooth'})}}>EXPLORAR O MAPA</button></div></div>}</>}
